// <auto-generated />
using System;
using HotelManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagement.API.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HotelManagement.API.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AttractionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attraction_id");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("author_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("HotelManagement.API.Models.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Article_Categories");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("distance_km");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("MapEmbedLink")
                        .HasColumnType("TEXT")
                        .HasColumnName("map_embed_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("HotelManagement.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_value");

                    b.Property<int>("RecordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("table_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("guest_phone");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelManagement.API.Models.BookingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_out_date");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_per_night");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_id");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Booking_Details");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BasePrice");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("DamagedQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DamagedQuantity");

                    b.Property<decimal?>("DefaultPriceIfLost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DefaultPriceIfLost");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrl");

                    b.Property<int?>("InStockQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InStockQuantity");

                    b.Property<int?>("InUseQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InUseQuantity");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ItemCode");

                    b.Property<int?>("LiquidatedQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LiquidatedQuantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Supplier")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Supplier");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalQuantity");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HotelManagement.API.Models.HotelBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("is_main");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("HotelBranches");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("FinalTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("final_total");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal?>("TotalRoomAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_room_amount");

                    b.Property<decimal?>("TotalServiceAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_service_amount");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HotelManagement.API.Models.LossAndDamage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BookingDetailId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("booking_detail_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrl");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_paid");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("penalty_amount");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int?>("RoomInventoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_inventory_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("RoomInventoryId");

                    b.ToTable("Loss_And_Damages");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("MinPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_points");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tier_name");

                    b.HasKey("Id");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("ReferenceLink")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_link");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HotelManagement.API.Models.OrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BookingDetailId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("booking_detail_id");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailId");

                    b.ToTable("Order_Services");
                });

            modelBuilder.Entity("HotelManagement.API.Models.OrderServiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("OrderServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_service_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Order_Service_Details");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_paid");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_code");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "manage_users"
                        },
                        new
                        {
                            Id = 2,
                            Name = "manage_roles"
                        },
                        new
                        {
                            Id = 3,
                            Name = "manage_rooms"
                        },
                        new
                        {
                            Id = 4,
                            Name = "manage_bookings"
                        },
                        new
                        {
                            Id = 5,
                            Name = "manage_services"
                        },
                        new
                        {
                            Id = 6,
                            Name = "view_reports"
                        },
                        new
                        {
                            Id = 7,
                            Name = "manage_housekeeping"
                        },
                        new
                        {
                            Id = 8,
                            Name = "view_own_bookings"
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_type_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "\"rating\" >= 1 AND \"rating\" <= 5");
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản trị viên hệ thống",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nhân viên lễ tân",
                            Name = "Receptionist"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhân viên dọn phòng",
                            Name = "Housekeeping"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Khách hàng",
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role_Permissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 8
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CleanStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("cleaning_status");

                    b.Property<int?>("Floor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("floor");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("room_number");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room_Images");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<decimal?>("PriceIfLost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_if_lost");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("QuantityDamaged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_damaged");

                    b.Property<int>("QuantityInUse")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_in_use");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Room_Inventory");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("BedType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("bed_type");

                    b.Property<int>("CapacityAdults")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity_adults");

                    b.Property<int>("CapacityChildren")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity_children");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal?>("SizeSqm")
                        .HasColumnType("TEXT")
                        .HasColumnName("size_sqm");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("ViewType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("view_type");

                    b.HasKey("Id");

                    b.ToTable("Room_Types");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomTypeAmenity", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_type_id");

                    b.Property<int>("AmenityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amenity_id");

                    b.HasKey("RoomTypeId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomType_Amenities");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("HotelManagement.API.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Service_Categories");
                });

            modelBuilder.Entity("HotelManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("membership_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MembershipId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vibecoding209@gmail.com",
                            FullName = "Admin System",
                            PasswordHash = "$2a$11$VQ8eIzRm2MjRl2gjFZWon.YQkCGooN1pMFhNEn6Yaf/PLq.nqkXIG",
                            RoleId = 1,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@hotel.com",
                            FullName = "Hotel Manager",
                            PasswordHash = "$2a$11$w0a9bylqBIL4UxKAX1DzLeHzGGcyv703ndlrU5eGKzey3jei38sP6",
                            RoleId = 1,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Email = "reception1@hotel.com",
                            FullName = "Receptionist 1",
                            PasswordHash = "$2a$11$moigqG6DqvHapVXW50MJ5.W1UeoELEqFL/nDBgIgbakaW.mG7DRoW",
                            RoleId = 2,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Email = "reception2@hotel.com",
                            FullName = "Receptionist 2",
                            PasswordHash = "$2a$11$moigqG6DqvHapVXW50MJ5.W1UeoELEqFL/nDBgIgbakaW.mG7DRoW",
                            RoleId = 2,
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            Email = "accountant@hotel.com",
                            FullName = "Accountant",
                            PasswordHash = "$2a$11$moigqG6DqvHapVXW50MJ5.W1UeoELEqFL/nDBgIgbakaW.mG7DRoW",
                            RoleId = 1,
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            Email = "hunglm@vaa.edu.vn",
                            FullName = "Hung Le",
                            PasswordHash = "$2a$11$moigqG6DqvHapVXW50MJ5.W1UeoELEqFL/nDBgIgbakaW.mG7DRoW",
                            RoleId = 4,
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            Email = "manhung08062@gmail.com",
                            FullName = "Manh Hung",
                            PasswordHash = "$2a$11$moigqG6DqvHapVXW50MJ5.W1UeoELEqFL/nDBgIgbakaW.mG7DRoW",
                            RoleId = 4,
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            Email = "dainguyen1254@gmail.com",
                            FullName = "Dai Nguyen",
                            PasswordHash = "$2a$11$moigqG6DqvHapVXW50MJ5.W1UeoELEqFL/nDBgIgbakaW.mG7DRoW",
                            RoleId = 4,
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            Email = "nguyenbinhan2707@gmail.com",
                            FullName = "An Nguyen",
                            PasswordHash = "$2a$11$moigqG6DqvHapVXW50MJ5.W1UeoELEqFL/nDBgIgbakaW.mG7DRoW",
                            RoleId = 4,
                            Status = true
                        });
                });

            modelBuilder.Entity("HotelManagement.API.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<string>("HolidayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("holiday_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("MembershipTier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("membership_tier");

                    b.Property<decimal?>("MinBookingValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_booking_value");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_limit");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_to");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("voucher_type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Article", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId");

                    b.HasOne("HotelManagement.API.Models.User", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId");

                    b.HasOne("HotelManagement.API.Models.ArticleCategory", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Attraction");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotelManagement.API.Models.AuditLog", b =>
                {
                    b.HasOne("HotelManagement.API.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Booking", b =>
                {
                    b.HasOne("HotelManagement.API.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId");

                    b.HasOne("HotelManagement.API.Models.Voucher", "Voucher")
                        .WithMany("Bookings")
                        .HasForeignKey("VoucherId");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("HotelManagement.API.Models.BookingDetail", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId");

                    b.HasOne("HotelManagement.API.Models.Room", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomId");

                    b.HasOne("HotelManagement.API.Models.RoomType", "RoomType")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomTypeId");

                    b.Navigation("Booking");

                    b.Navigation("Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Invoice", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("HotelManagement.API.Models.Invoice", "BookingId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelManagement.API.Models.LossAndDamage", b =>
                {
                    b.HasOne("HotelManagement.API.Models.BookingDetail", "BookingDetail")
                        .WithMany("LossAndDamages")
                        .HasForeignKey("BookingDetailId");

                    b.HasOne("HotelManagement.API.Models.RoomInventory", "RoomInventory")
                        .WithMany("LossAndDamages")
                        .HasForeignKey("RoomInventoryId");

                    b.Navigation("BookingDetail");

                    b.Navigation("RoomInventory");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Notification", b =>
                {
                    b.HasOne("HotelManagement.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagement.API.Models.OrderService", b =>
                {
                    b.HasOne("HotelManagement.API.Models.BookingDetail", "BookingDetail")
                        .WithMany("OrderServices")
                        .HasForeignKey("BookingDetailId");

                    b.Navigation("BookingDetail");
                });

            modelBuilder.Entity("HotelManagement.API.Models.OrderServiceDetail", b =>
                {
                    b.HasOne("HotelManagement.API.Models.OrderService", "OrderService")
                        .WithMany("OrderServiceDetails")
                        .HasForeignKey("OrderServiceId");

                    b.HasOne("HotelManagement.API.Models.Service", "Service")
                        .WithMany("OrderServiceDetails")
                        .HasForeignKey("ServiceId");

                    b.Navigation("OrderService");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Payment", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Review", b =>
                {
                    b.HasOne("HotelManagement.API.Models.RoomType", "RoomType")
                        .WithMany("Reviews")
                        .HasForeignKey("RoomTypeId");

                    b.HasOne("HotelManagement.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("RoomType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RolePermission", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagement.API.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Room", b =>
                {
                    b.HasOne("HotelManagement.API.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomImage", b =>
                {
                    b.HasOne("HotelManagement.API.Models.RoomType", "RoomType")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomTypeId");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomInventory", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Room", "Room")
                        .WithMany("RoomInventories")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomTypeAmenity", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Amenity", "Amenity")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagement.API.Models.RoomType", "RoomType")
                        .WithMany("RoomTypeAmenities")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Service", b =>
                {
                    b.HasOne("HotelManagement.API.Models.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotelManagement.API.Models.User", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Membership", "Membership")
                        .WithMany("Users")
                        .HasForeignKey("MembershipId");

                    b.HasOne("HotelManagement.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Membership");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Amenity", b =>
                {
                    b.Navigation("RoomTypeAmenities");
                });

            modelBuilder.Entity("HotelManagement.API.Models.ArticleCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelManagement.API.Models.BookingDetail", b =>
                {
                    b.Navigation("LossAndDamages");

                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Membership", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HotelManagement.API.Models.OrderService", b =>
                {
                    b.Navigation("OrderServiceDetails");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Room", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("RoomInventories");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomInventory", b =>
                {
                    b.Navigation("LossAndDamages");
                });

            modelBuilder.Entity("HotelManagement.API.Models.RoomType", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Reviews");

                    b.Navigation("RoomImages");

                    b.Navigation("RoomTypeAmenities");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Service", b =>
                {
                    b.Navigation("OrderServiceDetails");
                });

            modelBuilder.Entity("HotelManagement.API.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("HotelManagement.API.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("AuditLogs");

                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Voucher", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
